spring.application.name=Smart-Learning-Progress-Tracker
server.port=9090

spring.data.mongodb.uri=mongodb+srv://Dhanush2302:venom2302@progresstracker.wxpl1qs.mongodb.net/smart_learning_db?retryWrites=true&w=majority
